#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/common/generate-blob-scripts.sh - DO NOT EDIT

DEVICE=ideos

mkdir -p ../../../vendor/huawei/ideos/proprietary

DIRS="
bin
lib/hw
etc
"

for DIR in $DIRS; do
	mkdir -p ../../../vendor/huawei/ideos/proprietary/$DIR
done

FILES="
bin/akmd2
bin/load_oemlogo
bin/hci_qcomm_init
bin/modempre
bin/oem_rpc_svc
bin/qmuxd
bin/rild

etc/AudioFilter.csv
etc/init.qcom.bt.sh

lib/hw/gralloc.msm7k.so
lib/hw/sensors.ideos.so

lib/libaudioeq.so
lib/libcamera.so
lib/libcm.so
lib/libdiag.so
lib/libdll.so
lib/libdsm.so
lib/libdss.so
lib/libgsdi_exp.so
lib/libgstk_exp.so
lib/libhwrpc.so
lib/libmm-adspsvc.so
lib/libmmgsdilib.so
lib/libmmipl.so
lib/libmmjpeg.so
lib/libmm-omxcore.so
lib/libmmprocess.so
lib/libnv.so
lib/liboem_rapi.so
lib/libOmxCore.so
lib/libOmxH264Dec.so
lib/libOmxMpeg4Dec.so
lib/libOmxVidEnc.so
lib/libOmxWmvDec.so
lib/liboncrpc.so
lib/libpbmlib.so
lib/libqcamera.so
lib/libqmi.so
lib/libqueue.so
lib/libril.so
lib/libril-qc-1.so
lib/libril-qcril-hook-oem.so
lib/libwms.so
lib/libwmsts.so
"

for FILE in $FILES; do
    adb pull system/$FILE ../../../vendor/huawei/ideos/proprietary/$FILE
done

chmod 755 ../../../vendor/huawei/ideos/proprietary/bin/* 


(cat << EOF) | sed s/__DEVICE__/$DEVICE/g > ../../../vendor/huawei/$DEVICE/$DEVICE-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/__DEVICE__/extract-files.sh - DO NOT EDIT

# All the blobs necessary for Ideos
PRODUCT_COPY_FILES += \\
    vendor/huawei/__DEVICE__/proprietary/bin/akmd2:system/bin/akmd2 \\
    vendor/huawei/__DEVICE__/proprietary/bin/load_oemlogo:system/bin/load_oemlogo \\
    vendor/huawei/__DEVICE__/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \\
    vendor/huawei/__DEVICE__/proprietary/bin/modempre:system/bin/modempre \\
    vendor/huawei/__DEVICE__/proprietary/bin/oem_rpc_svc:system/bin/oem_rpc_svc \\
    vendor/huawei/__DEVICE__/proprietary/bin/qmuxd:system/bin/qmuxd \\
    vendor/huawei/__DEVICE__/proprietary/etc/AudioFilter.csv:system/etc/AudioFilter.csv \\
    vendor/huawei/__DEVICE__/proprietary/etc/init.qcom.bt.sh:system/etc/init.qcom.bt.sh \\
    vendor/huawei/__DEVICE__/proprietary/lib/hw/gralloc.msm7k.so:system/lib/hw/gralloc.msm7k.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/hw/sensors.ideos.so:system/lib/hw/sensors.ideos.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libcamera.so:obj/lib/libcamera.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libcamera.so:system/lib/libcamera.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libcm.so:system/lib/libcm.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libdiag.so:system/lib/libdiag.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libdll.so:system/lib/libdll.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libdsm.so:system/lib/libdsm.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libdss.so:system/lib/libdss.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libhwrpc.so:system/lib/libhwrpc.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libmm-omxcore.so:system/lib/libmm-omxcore.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libmmprocess.so:system/lib/libmmprocess.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libnv.so:system/lib/libnv.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libOmxCore.so:system/lib/libOmxCore.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libqcamera.so:system/lib/libqcamera.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libqmi.so:system/lib/libqmi.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libqueue.so:system/lib/libqueue.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libril.so:obj/lib/libril.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libril.so:system/lib/libril.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libwms.so:system/lib/libwms.so \\
    vendor/huawei/__DEVICE__/proprietary/lib/libwmsts.so:system/lib/libwmsts.so
EOF

./setup-makefiles.sh
